dependencies:
  - matplotlib
  - numpy
  - pandas
  - pip
  - pip:
    - RISE
    - nbzip
    - jupytext
    - rpy2
    - statsmodels
    - plotly
    - seaborn
    - jupyter_contrib_nbextensions
    - git+https://github.com/innovationOUtside/ipython_magic_blockdiag.git
    - git+https://github.com/innovationOUtside/nb_cell_execution_status.git
    - git+https://github.com/innovationOUtside/nb_extension_tagstyler.git
    - git+https://github.com/innovationOUtside/nb_extension_empinken.git
    - git+https://github.com/innovationOUtside/nb_cell_dialog.git
