dependencies:
  - matplotlib
  - numpy
  - pandas
  - pip
  -pip:
    - nbzip
    - jupytext
    - rpy2
    - statsmodels
    - plotly
    - seaborn
    - jupyter_contrib_nbextensions
    - git+https://github.com/innovationOUtside/ipython_magic_blockdiag.git
    - git+https://github.com/innovationOUtside/nb_cell_execution_status.git
